AWSTemplateFormatVersion: '2010-09-09'

Description: CloudFormation template to create an Amazon SQS FIFO queue

Parameters:
  QueueName:
    Type: String
    Default: MyFifoQueue.fifo
    Description: Name of the FIFO queue (must end with .fifo)

Resources:
  # SQS FIFO queue definition
  MyFifoQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref QueueName  # FIFO queue name (must end with .fifo)
      FifoQueue: true  # Specify that this is a FIFO queue
      ContentBasedDeduplication: true  # Enable content-based deduplication
      VisibilityTimeout: 30  # Time (in seconds) that a message is hidden after being received
      MessageRetentionPeriod: 345600  # Number of seconds to retain a message (4 days)
      DelaySeconds: 0  # No delivery delay

Outputs:
  QueueURL:
    Description: URL of the FIFO queue
    Value: !Ref MyFifoQueue

  QueueARN:
    Description: ARN of the FIFO queue
    Value: !GetAtt MyFifoQueue.Arn