AWSTemplateFormatVersion: '2010-09-09'

Description: CloudFormation template to create an Amazon SQS Standard Queue

Parameters:
  QueueName:
    Type: String
    Default: MyStandardQueue
    Description: Name of the Standard Queue

Resources:
  # SQS Standard Queue definition
  MyStandardQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Ref QueueName  # Standard queue name
      VisibilityTimeout: 30  # Time (in seconds) a message is invisible after being read
      MessageRetentionPeriod: 345600  # Time (in seconds) messages are retained (4 days)
      DelaySeconds: 0  # No delivery delay for new messages
      MaximumMessageSize: 262144  # Max message size in bytes (256 KB)

Outputs:
  QueueURL:
    Description: URL of the Standard Queue
    Value: !Ref MyStandardQueue

  QueueARN:
    Description: ARN of the Standard Queue
    Value: !GetAtt MyStandardQueue.Arn
