AWSTemplateFormatVersion: '2010-09-09'
# Description: Monitor Application Load Balancer using CloudWatch

# Parameters section defines input values used in the stack
Parameters:
  LoadBalancerName:
    Type: String
    Description: Name of the ALB to monitor
    Default: "STACK-NE-ALB-KdLBGAtCRTJ7"

  AutoScalingGroupName:
    Type: String
    Description: Name of the Auto Scaling Group to monitor
    Default: "STACK-NEW-AutoScalingGroup-F2IUN71ZGoRJ"

  TargetGroupName:
    Type: String
    Description: Name of the Target Group to monitor
    Default: "TG1"

  NotificationEmail:
    Type: String
    Default: 'ty780003@gmail.com'
    Description: Email for receiving CloudWatch alarm notifications (optional)

# Condition to check if an email address is provided for creating an SNS topic
Conditions:
  CreateSNSTopic: !Not [!Equals [!Ref NotificationEmail, ""]]

Resources:

  # SNS Topic for Notifications (only created if email is provided)
  AlarmSNSTopic:
    Type: AWS::SNS::Topic
    Condition: CreateSNSTopic
    Properties:
      Subscription:
        - Endpoint: !Ref NotificationEmail
          Protocol: email
      TopicName: "Alarmforloadbalancer"

  # Alarm for high average CPU utilization in the Auto Scaling Group
  HighASGCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "High-ASG-CPU"
      Namespace: AWS/AutoScaling
      MetricName: GroupAverageCPUUtilization
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref AutoScalingGroupName
      Statistic: Average
      Period: 300  # 5 minutes
      EvaluationPeriods: 1
      Threshold: 80  # 80% CPU
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - !If [CreateSNSTopic, !Ref AlarmSNSTopic, !Ref "AWS::NoValue"]

  # Alarm for high response latency from the Target Group
  TargetLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${TargetGroupName}-High-Latency"
      MetricName: TargetResponseTime
      Namespace: AWS/ApplicationELB
      Dimensions:
        - Name: TargetGroup
          Value: !Sub "targetgroup/${TargetGroupName}/*"
        - Name: LoadBalancer
          Value: !Sub "app/${LoadBalancerName}/*"
      Statistic: Average
      Period: 300  # 5 minutes
      EvaluationPeriods: 1
      Threshold: 1.0  # 1 second latency
      ComparisonOperator: GreaterThanThreshold
      AlarmDescription: "Triggers if average target response time exceeds 1 second"
      AlarmActions:
        - !If [CreateSNSTopic, !Ref AlarmSNSTopic, !Ref "AWS::NoValue"]

# Output section provides useful information after stack creation
Outputs:
  AlarmSNSTopicARN:
    Condition: CreateSNSTopic
    Description: SNS Topic ARN used for alarm notifications
    Value: !Ref AlarmSNSTopic