# AWSTemplateFormatVersion specifies the CloudFormation template version
AWSTemplateFormatVersion: '2010-09-09'

# Description of the CloudFormation template
Description: Request ACM SSL Certificate and DNS Validate using Route 53

# Parameters section defines user-supplied input values
Parameters:
  DomainName:
    Type: String
    Default: "mypotfolio.site"
    Description: Primary domain name for the certificate

  AlternativeName:
    Type: String
    Default: "www.mypotfolio.site"
    Description: (Optional) Alternative domain name

  HostedZoneId:
    Type: String
    Default: "Z01561572268UGRTCO72K"
    Description: Hosted Zone ID of the Route 53 domain

# Resources section contains the resources to be created
Resources:
  SSLCertificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName # Main domain for the certificate
      SubjectAlternativeNames:
        - !Ref AlternativeName # Additional domain name for the certificate
      ValidationMethod: DNS # Validation using DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName # DNS validation for primary domain
          HostedZoneId: !Ref HostedZoneId
        - DomainName: !Ref AlternativeName # DNS validation for alternative domain
          HostedZoneId: !Ref HostedZoneId

# Outputs section returns useful information after stack creation
Outputs:
  CertificateArn:
    Description: ARN of the ACM certificate
    Value: !Ref SSLCertificate # Returns the certificate ARN