# Specifies the CloudFormation template version
AWSTemplateFormatVersion: '2010-09-09'

Resources:
  # Creates an S3 bucket resource
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      # Sets the name of the bucket
      BucketName: my-public-versioned-glacier-bucket

      # Enables versioning for the bucket
      VersioningConfiguration:
        Status: Enabled

      # Enforces that the bucket owner has full control over all objects
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

      # Controls public access settings
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true         # Blocks new public ACLs
        IgnorePublicAcls: true        # Ignores existing public ACLs
        BlockPublicPolicy: false      # Allows public bucket policies
        RestrictPublicBuckets: false  # Does not restrict public bucket settings

      # Defines lifecycle rules for transitioning objects to cheaper storage classes over time
      LifecycleConfiguration:
        Rules:
          - Id: IAtoGlacierDeepArchive  # Unique ID for the lifecycle rule
            Status: Enabled             # Enables the rule
            Transitions:               # For current object versions
              - StorageClass: STANDARD_IA          # After 30 days, move to Infrequent Access
                TransitionInDays: 30
              - StorageClass: INTELLIGENT_TIERING  # After 60 days, move to Intelligent Tiering
                TransitionInDays: 60
              - StorageClass: ONEZONE_IA           # After 90 days, move to One Zone IA
                TransitionInDays: 90
              - StorageClass: GLACIER              # After 120 days, move to Glacier
                TransitionInDays: 120
              - StorageClass: DEEP_ARCHIVE         # After 210 days, move to Deep Archive
                TransitionInDays: 210
            NoncurrentVersionTransitions:          # For previous versions of objects
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
              - StorageClass: INTELLIGENT_TIERING
                TransitionInDays: 60
              - StorageClass: ONEZONE_IA
                TransitionInDays: 90
              - StorageClass: GLACIER
                TransitionInDays: 120
              - StorageClass: DEEP_ARCHIVE
                TransitionInDays: 210

  # Adds a bucket policy to allow public read access
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket  # Refers to the bucket created above
      PolicyDocument:
        Statement:
          - Sid: PublicReadGetObject          # Unique ID for the statement
            Effect: Allow                     # Allows the action
            Principal: "*"                   # Applies to all users
            Action: "s3:GetObject"            # Allows only GetObject action
            Resource: !Sub "${MyS3Bucket.Arn}/*"  # Applies to all objects in the bucket