# AWSTemplateFormatVersion specifies the version of the CloudFormation template format
AWSTemplateFormatVersion: '2010-09-09'

# Description of what the CloudFormation stack will do
Description: CloudFront Distribution for a Single Public Website with an ELB Origin (No Security Protections)

Parameters:
  # ELBDomainName is the DNS of the public Elastic Load Balancer used as the CloudFront origin
  ELBDomainName:
    Description: DNS name of the public Elastic Load Balancer (e.g., my-load-balancer-1234567890.us-east-1.elb.amazonaws.com)
    Type: String
    Default: "auto-sca-ALB-yeh9TB20OUo2-814420290.us-east-1.elb.amazonaws.com"

Resources:
  # Creates a CloudFront distribution resource
  MyCloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true  # Enables the distribution
        Origins:
          - Id: PublicELBOrigin  # Logical ID for the origin
            DomainName: !Ref ELBDomainName  # References the ELB DNS name
            CustomOriginConfig:
              HTTPPort: 80  # HTTP port used for origin connection
              HTTPSPort: 443  # HTTPS port used for origin connection
              OriginProtocolPolicy: https-only  # CloudFront communicates with origin using HTTPS only
        DefaultCacheBehavior:
          TargetOriginId: PublicELBOrigin  # Uses the origin defined above
          ViewerProtocolPolicy: redirect-to-https  # Redirects HTTP requests to HTTPS
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          Compress: true  # Enables compression to reduce payload size
          ForwardedValues:
            QueryString: true  # Forwards query strings to the origin
            Cookies:
              Forward: none  # Does not forward cookies to origin
        DefaultRootObject: index.html  # Serves index.html when no object is specified
        ViewerCertificate:
          CloudFrontDefaultCertificate: true  # Uses default CloudFront certificate (no custom SSL)
        PriceClass: PriceClass_100  # Limits distribution to US, Canada, and Europe
        HttpVersion: http2  # Enables HTTP/2 support

Outputs:
  # Outputs the DNS name of the CloudFront distribution
  CloudFrontDomainName:
    Description: CloudFront Distribution Domain Name
    Value: !GetAtt MyCloudFrontDistribution.DomainName