# This CloudFormation template creates a Route 53 Alias Record for a CloudFront distribution
# 
# AWSTemplateFormatVersion specifies the version of the CloudFormation template format
# Description provides a brief about the purpose of the template
AWSTemplateFormatVersion: '2010-09-09'
Description: Create Route 53 Alias Record to point to a CloudFront distribution

# Parameters allow users to input values when launching the stack
# HostedZoneId is the ID of the Route 53 hosted zone where the alias record will be created
# RecordName is the DNS name (e.g., www.example.com) to map to the CloudFront distribution
# CloudFrontDomainName is the domain name of the CloudFront distribution (e.g., dxxxxx.cloudfront.net)
Parameters:
  HostedZoneId:
    Description: "The ID of your Route 53 Hosted Zone (e.g., Z123456ABCDEFG)"
    Type: String
    Default: Z01561572268UGRTCO72K

  RecordName:
    Description: "Record name to create (e.g., www.myportfolio.site or myportfolio.site)"
    Type: String
    Default: "mypotfolio.site"

  CloudFrontDomainName:
    Description: "CloudFront Distribution Domain Name (e.g., dxxxxx.cloudfront.net)"
    Type: String
    Default: "d3688u1bk0c7jz.cloudfront.net"

# Resources section defines the Route 53 alias record
# CloudFrontAliasRecord is the logical name of the Route 53 record being created
# Type AWS::Route53::RecordSet indicates a DNS record
# HostedZoneId specifies the hosted zone in which to create the record
# Name sets the DNS name for the alias
# Type A indicates an IPv4 address record
# AliasTarget defines the target CloudFront distribution and its hosted zone ID
Resources:
  CloudFrontAliasRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref RecordName
      Type: A
      AliasTarget:
        DNSName: !Ref CloudFrontDomainName
        HostedZoneId: Z2FDTNDATAQYW2  # CloudFront’s hosted zone ID is always Z2FDTNDATAQYW2 for alias records