AWSTemplateFormatVersion: '2010-09-09'
Resources:
  MyInstance: # Defines an EC2 instance resource
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-02457590d33d576c3  # AMI ID for the EC2 instance
      InstanceType: t2.micro          # Instance type
      KeyName: navkarannewaccountverginea  # EC2 Key Pair name for SSH access
      SecurityGroupIds: # Security Group(s) associated with the instance
        - sg-046247cc667432a09
      UserData: # User data script to be executed on instance launch
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y                                                # Update yum packages
          yum install httpd -y                                         # Install Apache HTTP Server
          systemctl start httpd                                        # Start Apache service
          systemctl enable httpd                                       # Enable Apache to start on boot
          echo "hello world" > /var/www/html/index.html                # Create a simple HTML file